# ['fbresnet152', 'bninception', 'resnext101_32x4d', 'resnext101_64x4d', 'inceptionv4', 'inceptionresnetv2',
# 'alexnet', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'resnet18', 'resnet34', 'resnet50',
# 'resnet101', 'resnet152', 'inceptionv3', 'squeezenet1_0', 'squeezenet1_1', 'vgg11', 'vgg11_bn', 'vgg13',
# 'vgg13_bn', 'vgg16', 'vgg16_bn', 'vgg19_bn', 'vgg19', 'nasnetamobile', 'nasnetalarge', 'dpn68', 'dpn68b', 'dpn92',
# 'dpn98', 'dpn131', 'dpn107', 'xception', 'senet154', 'se_resnet50', 'se_resnet101', 'se_resnet152',
# 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'cafferesnet101', 'pnasnet5large', 'polynet']

TRAIN_DIR: '_results/resnet34_256_480_crop_pad'

DATA_DIR: 'data/crop'
CSV: 'data/stratified/5fold_0.csv'

PARALLEL: False
NUM_WORKERS: 2
DEBUG: False
VALIDATE_CHECKPOINT : 'checkpoints/epoch_0053_0.9428.pth'

MIXUP: False
DATA:
  NAME: 'CarDataset'
  IMG_H: 256
  IMG_W: 480

MODEL:
  NAME: 'se_resnext50_32x4d'
  PRETRAINED: True

TRAIN:
  BATCH_SIZE: 16
  NUM_EPOCHS: 100

EVAL:
  BATCH_SIZE: 64

LOSS:
  NAME: 'binary_focal_loss'

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001
  PARAMS:
    weight_decay: 0

SCHEDULER:
  NAME: 'cosine'
  PARAMS:
#    milestones: [50, 75]
#    gamma: 0.1

    T_max: 8
    eta_min: 0.00001

