# ['fbresnet152', 'bninception', 'resnext101_32x4d', 'resnext101_64x4d', 'inceptionv4', 'inceptionresnetv2',
# 'alexnet', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'resnet18', 'resnet34', 'resnet50',
# 'resnet101', 'resnet152', 'inceptionv3', 'squeezenet1_0', 'squeezenet1_1', 'vgg11', 'vgg11_bn', 'vgg13',
# 'vgg13_bn', 'vgg16', 'vgg16_bn', 'vgg19_bn', 'vgg19', 'nasnetamobile', 'nasnetalarge', 'dpn68', 'dpn68b', 'dpn92',
# 'dpn98', 'dpn131', 'dpn107', 'xception', 'senet154', 'se_resnet50', 'se_resnet101', 'se_resnet152',
# 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'cafferesnet101', 'pnasnet5large', 'polynet']

TRAIN_DIR: '_results/se_resnext50_32x4d_256_480_crop_only_weak_aug_addfc_5fold_2'

DATA_DIR: 'data/crop'
CSV: 'data/stratified/5fold_2.csv'

PARALLEL: True
NUM_WORKERS: 4
DEBUG: False
MIXUP: False

DATA:
  NAME: 'CarDataset'
  IMG_H: 256
  IMG_W: 480

MODEL:
  NAME: 'se_resnext50_32x4d'
  ADD_FC: True

TRAIN:
  BATCH_SIZE: 128
  NUM_EPOCHS: 35

EVAL:
  BATCH_SIZE: 512

LOSS:
  NAME: 'binary_focal_loss'

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001
  PARAMS:
    weight_decay: 0

SCHEDULER:
  NAME: 'cosine'
  PARAMS:
#    milestones: [4, 14]
#    gamma: 0.1

    T_max: 10
    eta_min: 0.00001

